version: "3.3"

services:
  app:
    build: 
      dockerfile: Dockerfile
      context: .
    image: backend-go-aljun
    container_name: be-aljun
    ports:
      - 1324:1323
    restart: "unless-stopped"
    tty: true
    networks:
      - sppnetwork

networks:
  sppnetwork:
    driver: bridge
